### ISSUE TITLE
SpringBoot 2.x, JUnit5 and DatabaseRider configuration woes

### ISSUE THREAD

**Issue by mutsys** [database-rider/database-rider#183]
It seems that getting this combination of tools to work together isn't sufficiently documented, I found the examples to be lacking. However, after a couple of hours of experimentation I was able to assemble a meta-annotation for myself that works as expected:

```java
@SpringJUnitConfig
@DBUnit(
    caseInsensitiveStrategy = Orthography.LOWERCASE,
    cacheConnection = false,
    dataTypeFactoryClass = PostgresqlDataTypeFactory.class
)
@TestExecutionListeners(
    value = {
        DBRiderTestExecutionListener.class,
        TransactionalTestExecutionListener.class,
        DependencyInjectionTestExecutionListener.class,
        DirtiesContextTestExecutionListener.class
    },
    mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS
)
@DirtiesContext
@SpringBootTest(
    webEnvironment= SpringBootTest.WebEnvironment.NONE
)
@Transactional
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
public @interface DBIntegrationTest {
}
```
Am I doing too much configuration here? Is there something I missed? I'm glad that I was able to find a working configuration, but the samples/examples that I have seen published lead me to believe that a simpler configuration should have been possible...

**Comment by rmpestano** [comment]
Hi @mutsys, thanks for the feedback!

What issues you had with the [SpringBoot Junit5 example](https://github.com/database-rider/database-rider/tree/master/rider-examples/spring-boot-dbunit-sample)? 

Also, what do you miss on the [JUnit5 docs](https://github.com/database-rider/database-rider#7-junit-5)? maybe we can add a SpringBoot section there

**Comment by mutsys** [comment]
The first thing I tried was to emulate this example:

https://github.com/database-rider/database-rider/blob/master/rider-examples/spring-boot-dbunit-sample/src/test/java/com/github/database/rider/springboot/SpringBootDBUnitTest.java

My tests were either failing or generating a false positive result because although the tests have dbrider hooked into the junit 5 test lifecycle, they are NOT hooked into the spring test lifecycle. Look closely at the import statements for the example, specifically:

`import com.github.database.rider.junit5.api.DBRider;`

Now if I change that import statement to this:

`import com.github.database.rider.spring.api.DBRider;`

I am now hooked into the spring lifecycle but not the junit 5 lifecycle.

In order to work with both junit 5 and spring, I need to do the following:

```java
@SpringJUnitConfig
@DBRider
@SpringBootTest
```
with the latter of the import statements. But now this **still** won't work because some tests fail due to what appears to be a connection leak somewhere in DBRider. Flagging the spring context as dirty at the end of each test and refreshing it eliminates the connection leak.

```java
@SpringJUnitConfig
@DBRider
@SpringBootTest
@DirtiesContext
@TestExecutionListeners(
        value = {
                DirtiesContextTestExecutionListener.class
        }
)
```

but now some tests seem to just run and generate false positives, others outright fail with little to no information in the console about how or why they failed. However, it seems pretty clear that since the errors occur on lines of code that access attributes of JPA entities, something is wrong with the injection of my JPA repository into the test instance. OK, so let's make sure that test dependencies are getting injected.

```java
@SpringJUnitConfig
@DBRider
@SpringBootTest
@DirtiesContext
@TestExecutionListeners(
        value = {
                DependencyInjectionTestExecutionListener.class,
                DirtiesContextTestExecutionListener.class
        }
)
```
still failing with similar mysterious exceptions. What else is missing? Well, perhaps spring test transaction management?

```java
@SpringJUnitConfig
@DBRider
@SpringBootTest
@DirtiesContext
@Transactional
@TestExecutionListeners(
        value = {
                TransactionalTestExecutionListener.class,
                DependencyInjectionTestExecutionListener.class,
                DirtiesContextTestExecutionListener.class
        }
)
```
still failing again with mysterious exceptions. Now this is not my first experience with these tools, except for DBRider. I had previously been successful with `spring-test-dbunit` and know the configuration for tests pretty well. The only thing that is different here is the `@DBRider` annotations. So how about I open that up and add its elements directly to my test and see what happens?

```java
@SpringJUnitConfig
@SpringBootTest
@DirtiesContext
@Transactional
@TestExecutionListeners(
        value = {
                DBRiderTestExecutionListener.class,
                TransactionalTestExecutionListener.class,
                DependencyInjectionTestExecutionListener.class,
                DirtiesContextTestExecutionListener.class
        },
        mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS
)
```
Success!!!! After this point I performed a few more experiments, removing various components of the configuration to see if any lesser configuration would be successful but each attempt failed.

**Comment by rmpestano** [comment]
Thank you very much for the detailed feedback, I'll try to reproduce the issues you had, mainly the connection leak that may be caused by DBRider.

What version of SpringBoot are you using?

**Comment by rmpestano** [comment]
Hi again @mutsys,

sorry for the late reply but I tried to simulate our issue in [SpringBoot JUnit 5 sample](https://github.com/database-rider/database-rider/blob/master/rider-examples/spring-boot-dbunit-sample/src/test/java/com/github/database/rider/springboot/SpringBootDBUnitTest.java) example but could not reproduce.

I don't understand you statement:

> although the tests have dbrider hooked into the junit 5 test lifecycle, they are NOT hooked into the spring test lifecycle.

We're using SpringBoot JUnit5 extension to retrieve datasource connection, [see here](https://github.com/database-rider/database-rider/blob/16dc93a04d521594032b9a2c7750f3f84d2aebbd/rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java#L136-L139), that's how we integrate with SpringBoot.

So that's why you should **not** use `@DBRider` from `spring` module.

> Now if I change that import statement to this:
import com.github.database.rider.spring.api.DBRider;
I am now hooked into the spring lifecycle but not the junit 5 lifecycle.


Can you try to reproduce one of the issues you had in SpringBoot JUnit 5 sample or maybe another simple reproduced where I can see issue? 

Again sorry for the late reply and thank you for the feedback!

**Comment by mutsys** [comment]
no problem. i will put together an example repo for you that reproduces the issue.

**Comment by arhohuttunen** [comment]
I was investigating another issue and ran into a little similar problem. I think there's a problem when using Spring `@Transactional` for tests together with database rider.

An easy way to reproduce is to take [SpringBoot JUnit 5 sample](https://github.com/database-rider/database-rider/blob/master/rider-examples/spring-boot-dbunit-sample/src/test/java/com/github/database/rider/springboot/SpringBootDBUnitTest.java) and change `@SpringBootTest` to `@DataJpaTest`, or just add `@Transactional` annotation. Now, the expected database checks start failing:

```
junit.framework.ComparisonFailure: row count (table=USERS) expected:<[1]> but was:<[0]>
```

**Comment by rmpestano** [comment]
Hi, but [UserRepository](https://github.com/database-rider/database-rider/blob/aa142b4a4cabb47589ad222c150ad73ea59453c5/rider-examples/spring-boot-dbunit-sample/src/main/java/com/github/database/rider/springboot/model/user/UserRepository.java#L7) already has `@Transactional`, why do you need It on the test?

**Comment by arhohuttunen** [comment]
It's just an alternative to produce the same results as using `@DataJpaTest`. From Spring Boot docs: [By default, tests annotated with @DataJpaTest are transactional and roll back at the end of each test.](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/orm/jpa/DataJpaTest.html)

You can specifically make them non-transactional by adding `@Transactional(propagation = Propagation.NOT_SUPPORTED)` but that's the default behaviour.

**Comment by arhohuttunen** [comment]
I wasn't aware that the JUnit 5 module is not hooking into to the Spring transaction context. The workaround would be to disable transactions in the tests and add some `cleanBefore=true` into test methods, but for example in a current project all our db tests are using `@DataJpaTest` and depending on the tests to be rolled back. We were accidentally using `rider-spring` there so it was kind of working.

It would be quite nice if there was a way to both use JUnit 5 and hook into the Spring transaction management. `@DataJpaTest` is a pretty standard annotation, so it would enable support for that out-of-the-box.

**Comment by rmpestano** [comment]
Maybe we can try to integrate with transaction context but question why the rollback is important. In a dbunit context the default seeding strategy is `CLEAN_INSERT` which means that in most of the cases you don't need clean before.

**Comment by rmpestano** [comment]
One thing that I saw in this [SO answer ](https://stackoverflow.com/a/10108123/1260910) is that you can use `qualifiedTableNames`, maybe that helps as well:

`@DBUnit(qualifiedTableNames = true)`

**Comment by arhohuttunen** [comment]
At least it would be compatible with `@DataJpaTest` then. The `@DBRider` in `rider-spring` and `rider-junit5` are not consistent in that sense now.

But yes, I agree that in most cases you don't need clean before. There are just some cases where your datasets don't necessarily have all the tables that the test touches, so you'd have to add empty tables in the dataset in order to not get any foreign key violations, or add clean before. There might also be tests that don't set a dataset, but might only check for the expected database.

I was actually thinking that it would be _better_ if the tests were non-transactional, but that's the Spring default for that annotation anyway.

**Comment by rmpestano** [comment]
I still not sure I want to add behavior that is already solved by DBUnit in a different way. I mean, for me, it doesn't make sense to roll back in a dbunit test because the next test will prepare the database state by itself.

>  The @DBRider annotations in rider-spring and rider-junit5 are not consistent in that sense now.

Yes, I agree and by what I said above I would prefer to change rider-spring instead of junit5.

Anyone else has thoughs about that? cc @njuro

**Comment by arhohuttunen** [comment]
I agree, this is something  only Spring specific.

A lot of this was hidden because I didn't know that `@DataJpaTest` adds a `@Transactional` annotation, and now I'm considering changing the default and cleaning up some tests the dbunit way. They mostly already work because of the default seeding strategy anyway.
