### ISSUE TITLE
Possible security issue: hard-coded password

### ISSUE THREAD

**Issue by akondasif** [database-rider/database-rider#218]
Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of hard-coded passwords. According to [CWE](https://cwe.mitre.org/data/definitions/259.html), "A hard-coded password typically leads to a significant authentication failure that can be difficult for the system administrator to detect." 

Hopefully, you agree and will fix it.

Source: https://github.com/database-rider/database-rider/blob/master/rider-examples/quarkus-dbunit-sample/src/main/resources/application.properties

**Comment by kayman-mk** [comment]
Indeed this is a good point everybody should consider in a project. Plaintext passwords are bad. But I think this issue is not 100% relevant here as the Quarkus app is just a showcase for Database Rider. Thus it is fine to have plaintext passwords in the configuration to make things easy.

From my point of view it is worth the time to add a note for the inexperienced users, so they are aware of this point and use encrypted passwords, a credential provider, ... or something else.

**Comment by rmpestano** [comment]
Thank you guys for looking into it, yes I think adding a remark is enough
