### ISSUE TITLE
Question: How to get the right sequences after inserting datasets

### ISSUE THREAD

**Issue by duschata** [database-rider/database-rider#236]

**Comment by duschata** [comment]
Hello All, 

I would like to replace tests which uses the arquillian-persistence-extension with RiderDSL-tests to create my tables and fill them with initial values.
After filling the database, no data can be inserted via JPA into the (H2) database. I get following exceptions:

SQL Error: 23502, SQLState: 23502, NULL not allowed for column "ID"; SQL statement:

I think that this behavior is because RiderDSL does not generate any detailed sequences as you can see here :

![image](https://user-images.githubusercontent.com/11717747/93761071-71aa9300-fc0d-11ea-8884-a6a3f461e045.png)

but the the data generated from the origin arquillian test is like this:

![image](https://user-images.githubusercontent.com/11717747/93761163-9999f680-fc0d-11ea-8199-78de9c2b16b4.png)

Please give me a hint why the arquillian-persistence-extension generates this sequences (I suppose this) but the DSLRider not?

**Comment by rmpestano** [comment]
Hello,

All Rider tests are using JPA ;) 

I think your issue is how to create the tables because that will not be done by DBRider. In RiderTests we use an utility called EntityManagerProvider, see here in [RiderDSL tests](https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/test/java/com/github/database/rider/core/dsl/RiderDSLIt.java#L34), in this case db tables will be created by JPA `drop-and-create` strategy, [see here](https://github.com/database-rider/database-rider/blob/29c38f29655a31a6b09d7305aec6a6237d87be73/rider-core/src/test/resources/META-INF/persistence.xml#L15).

Maybe if you share a sample project we can help you further

**Comment by duschata** [comment]
Hello All, hello Rafael,

Ok, the question may have been a little bit unclear. 
I'll try again, Have a look to my dummy-project: [here](https://github.com/duschata/riderDSLSequences)

After the database tables have been created (via jpa), I add initial data records. 

https://github.com/duschata/riderDSLSequences/blob/master/src/test/java/RiderTest.java#L29-L44

A new entity is  created and the persist method called. This method throws a ConstraintViolationException because it has the annotation "@GeneratedValue (strategy = GenerationType.AUTO)". 

https://github.com/duschata/riderDSLSequences/blob/master/src/main/java/model/CoreEntity.java#L15-L18

The value of the sequence table is 0, so the next value is 1, this key already exists and cannot be inserted.

![image](https://user-images.githubusercontent.com/11717747/94116461-604eca00-fe4b-11ea-9f22-53cab99ebf63.png)

In contrast to this, the arquillian in my productive-project-tests, which are annotated with @UsingDataSet (...), have correct sequences which are generated for each table and the inserts also work.
The question is, "Why is the behavior like this?" Is that the default or is there a hook in my productive-project that I can't detect?

You can see see the sequence-table in the previous post (many records one for each table)

**Comment by rmpestano** [comment]
Hi @duschata,

Just use negative ids so they will not conflict with sequence table (for example negative IDs like -1,-2 etc..).

One thing that I noticed is that if you use any value as `tableOrdering`, the test will pass:
 
```
 DataSetConfig datasetConfig = new DataSetConfig("user.xml", "other.xml");
        datasetConfig.
                cleanAfter(false).
                tableOrdering("BLABLA").
                cleanBefore(true).
                disableConstraints(true).
                strategy(SeedStrategy.CLEAN_INSERT);
```

I don't know why, the only difference is that DBRider will use a `SequenceTableFilter` to create the DBUnit IDataSet implementation:

```
  if (dataSet.getTableOrdering().length > 0) {
            target = new FilteredDataSet(new SequenceTableFilter(dataSet.getTableOrdering(), dbUnitConfig.isCaseSensitiveTableNames()), target);
        }
``` 

Maybe that makes a difference but tableOrdering is used for another usecase.

I hope it helps.

**Comment by duschata** [comment]
Hello All, 
the usage of negative ids is a good quickfix for me. The tableOrdering "BLABLA" deletes all data before inserting the new dataset and this is probably not the best way to avoid the id-conflict :-)
If I find the the hook, which is responsible for the right sequence ids, then I'll get back to you...

**Comment by duschata** [comment]
I've found it... 

`<property name="hibernate.id.new_generator_mappings" value="false" /> `

is hibernate specific but generates sequences for each table...

**Comment by rmpestano** [comment]
Thanks for the update @duschata!

**Comment by luisalves00** [comment]
@rmpestano I'm using:

```java
@ExtendWith(DBUnitExtension.class)
public class CompanyTest extends SpringComponentTest {
```

with:

```java
    @Id
    @GeneratedValue(generator = "company_id_seq", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "company_id_seq", sequenceName = "company_id_seq", allocationSize = 10)
    @Column(name = "id", nullable = false, unique = true)
    private Long id;
```

And on the Dataset if I don't provide and ID I get:

Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "ID"; SQL statement:

So I assume the sequence is not being used. The negative id does the trick, thanks for the hint.

What I would like to understand is if database rider should be using the sequences (and when explicitly setting an id, updating the sequence) or not? I might have some bad config preventing it from working.

**Comment by rmpestano** [comment]
Hi @luisalves00, dbrider is not using sequence generators, the issue is that sometimes the pk you use in your datasets conflicts with IDs generated by sequence generators. The solution is to either clean the sequence table and reset the generator or use PKs that don't conflict with the generated IDs.
