### ISSUE TITLE
Operations on table isn't executed when merge datasets is used

### ISSUE THREAD

**Issue by RomashkoVictor** [database-rider/database-rider#247]
Hi everyone.
I user **MergeDatasets** feature and if I use class level dataset with empty tables, data from method level dataset will not be inserted.
Here is sorce files:
Base test class
```
@DBRider
@DataSet(value = "datasets/empty.yml", tableOrdering = {"first_table", "second_table", "third_table"})
abstract class BaseTest {
```
Child test class
```
public class ChildTest extends BaseTest { 
@Test
@DataSet(value = "datasets/dataset_with_data.yml", useSequenceFiltering = false)
@ExpectedDataSet(value = "datasets/dataset_with_data.yml", orderBy = "id")
void childTest() throws Exception {
```
empty.yml
```
first_table:
second_table:
third_table:
```
dataset_with_data.yml
```
first_table:
  - name: first_record
  - name: second_record

second_table:
  - name: first_record
  - name: second_record
```

I want to use empty.yml file to simplify cliening of database(I use clean_insert strategy) and don't duplicate empty tables in every dataset. Properties `@DataSet(cleanBefore, cleanAfter)` cannot be used, as they clear more tables, than we used.

Why operation isn't executed:
DataSetExecutorImpl
```
@Override
    public void createDataSet(DataSetConfig dataSetConfig) {
...
operation.execute(getRiderDataSource().getDBUnitConnection(), resultingDataSet);
```
CompositeOperation
```
public void execute(IDatabaseConnection connection, IDataSet dataSet)
            throws DatabaseUnitException, SQLException
    {
        logger.debug("execute(connection={}, , dataSet={}) - start", connection, dataSet);

        for (int i = 0; i < _actions.length; i++)
        {
            DatabaseOperation action = _actions[i];
            action.execute(connection, dataSet);
        }
    }
```
AbstractBatchOperation
```
@Override
    public void execute(IDatabaseConnection connection, IDataSet dataSet)
            throws DatabaseUnitException, SQLException
    {
        logger.debug("execute(connection={}, dataSet={}) - start", connection,
                dataSet);

        DatabaseConfig databaseConfig = connection.getConfig();
        IStatementFactory factory = (IStatementFactory) databaseConfig
                .getProperty(DatabaseConfig.PROPERTY_STATEMENT_FACTORY);
        boolean allowEmptyFields = connection.getConfig()
                .getFeature(DatabaseConfig.FEATURE_ALLOW_EMPTY_FIELDS);

        // for each table
        ITableIterator iterator = iterator(dataSet);
        while (iterator.next())
        {
            ITable table = iterator.getTable();

            String tableName = table.getTableMetaData().getTableName();
            logger.trace("execute: processing table='{}'", tableName);

            // Do not process empty table
            if (isEmpty(table))
            {
                continue;
            }
```

There is check that we shouldn't process the empty tablse, but in our situation we have CompositeTable, but it's **_metaData** is from first table( that is from empty.yml) and we skip table processing in spite the second table contains data.

The root cause here:
CompositeTable
```
/**
     * Creates a composite table that combines the specified specified tables.
     * The metadata from the first table is used as metadata for the new table.
     */
    public CompositeTable(ITable table1, ITable table2) {
        _metaData = table1.getTableMetaData();
        _tables = new ITable[] {table1, table2};
    }
```
As a result we didn't use methadata from second table.
Can we merge methadata from both tables?

**Comment by rmpestano** [comment]
Hi, 

> Why operation isn't executed:

In your case `datasets/dataset_with_data.yml` operation will be performed first so both `first_table` and `second_table` will be populated, then afterwards empty.yml operation is executed and then all tables are cleaned. Is that behavior you're seeing?

**Comment by RomashkoVictor** [comment]
As I see no operation will be performed at all. We skip all tables here
```
if (isEmpty(table))
{
  continue;
}
```

What I want of this code - to clear all tables with which I work by default.
Workaroud, that I use now is to execute scripts after or before where I clean all data from tables. The issue is that I should support `tableOrdering` property and script, but both used only to order insert, clean data to tables.

**Comment by rmpestano** [comment]
Sorry, I cannot follow your reasoning, this code is from DBUnit itself but I don't think the problem you're facing is related to it.

If you provide a test case with expected results, I can try to help, for now, as I said before, I think your issue is related to the order of operations from datasets defined at class and method level.

**Comment by RomashkoVictor** [comment]
Test class DataSetExecutorIt
This test case is failed and reproduce issue, that I have
```
@Test
    public void shouldLoadUserWithEmptyDataset() {
        DataSetConfig DataSetConfig = new DataSetConfig("datasets/yml/empty.yml", "datasets/yml/users.yml");
        executor.createDataSet(DataSetConfig);
        User user = (User) EntityManagerProvider.em().createQuery("select u from User u where u.id = 1").getSingleResult();
        assertThat(user).isNotNull();
        assertThat(user.getId()).isEqualTo(1);
        assertThat(user.getTweets()).isNotNull().hasSize(1);
        Assert.assertEquals(user.getTweets().get(0).getContent(), "dbunit rules!");
        assertThat(user.getFollowers()).isNotNull().hasSize(1);
        Follower expectedFollower = new Follower(2,1);
        assertThat(user.getFollowers()).contains(expectedFollower);
    }
```

We can try to fix issue in DataSetExecutorImpl.loadDataSets method.

**Comment by rmpestano** [comment]
So, as the table USER is present in both datasets that's why ordering matters. To fix, just remove `USER` table from empty.yml because the table is already present there.

I think your problem is that you're trying to reuse too much the datasets in too many different scenarios. Just create specific datasets and you'll be ok.

**Comment by RomashkoVictor** [comment]
`empty.yml` dataset is shared between all tests. So I cannot just remove `User` table from empty.yml dataset, as in other test it must be empty.

May be I try to reuse too much. I will describe situation, why I try to do so.
We use clean_insert strategy and our tests run in different order. To clear table in test we should also clear all dependent tables. So in every dataset we have many empty tables. All is work prety good.
But then we add table that is depende on `User` table, and now we should edit every dataset and place empty new table. We have 70 test cases and plan to expand this type of tests.
And every time when we want to add table we will not want to edit all existed datasets.

So I try to add `empty.yml` dataset where we will place **once** new table and it will be cleared in every test case.

**Comment by rmpestano** [comment]
So maybe if datasets at class level are loaded first your issue is solved. 

If that's the case then maybe we can add a property in `dbunit.yml`/`@DBUnit` to invert the order of execution in merge datasets like:

```
loadClassLevelDataSetsFirst=true //not sure the name
cacheConnection: false
cacheTableNames: false
leakHunter: true
raiseExceptionOnCleanUp: true
expectedDbType: HSQLDB
properties:
  batchedStatements:  true
  caseSensitiveTableNames: false
  qualifiedTableNames: true
... other properties
```

**Comment by RomashkoVictor** [comment]
In my case it will be enough. But I afraid, that somebody will have both situations. Where class level dataset will be empty and method level.

**Comment by rmpestano** [comment]
Yea but for me it makes more sense to first load `classLevel` datasets because then you can override their behavior in the method level. You can even have a default USER table data in all datasets but if you want different users in a specific test you can just override the class level dataset in a specific test via method level merging. 

On the other hand, as the merging is done now the more specific datasets (methods level) are loaded first and then the more generic ones (probably in a super class) are loaded later.

But of course, we cannot change this behavior now because we'll break everyone, so I'll add a property to be able to control the order of merging called `mergingStrategy` which can be CLASS or METHOD:

```
@RunWith(JUnit4.class)
@DataSet(value = "yml/empty.yml")
@DBUnit(mergeDataSets = true, mergingStrategy = DataSetMergingStrategy.CLASS)
public class MergeDataSetClassLevelFirstIt {

    @Rule
    public EntityManagerProvider emProvider = EntityManagerProvider.instance("rules-it");

    @Rule
    public DBUnitRule dbUnitRule = DBUnitRule.instance(emProvider.connection());

    @Test
    @DataSet(value = "yml/user.yml")
    public void shouldMergeDataSetsFromClassAndMethod() {
        List<User> users = em().createQuery("select u from User u").getResultList();
        assertThat(users).isNotNull().isNotEmpty().hasSize(2);//2 because user.yaml dataset is loaded after empty.yml
    }
}
```

For global configuration `src/test/resources/dbunit.yml` you can set like below:

```
mergingStrategy: CLASS
``` 

This should be available in `1.17.1-SNAPSHOT` as soon the [current build](https://travis-ci.org/github/database-rider/database-rider/builds/742769216) finishes and hopefully passes.

**Comment by RomashkoVictor** [comment]
Great Thanks!)
For me it makes more sense to first load `classLevel` datasets too. It is usuall behavior of Spring annotations, where class level loaded first and can be overriden by method level.

**Comment by rmpestano** [comment]
Can you try using the `mergingStrategy` to see if that works for you? you may need to update the snapshots with `mvn -U test`

**Comment by RomashkoVictor** [comment]
I checked new version it solve my issue completly)
Thanks.

**Comment by RomashkoVictor** [comment]
Some usefull comments of usage DBrider, that you may add to documentation in version 1.17.1
To improve speed of test execution, use abstract BaseTest class with configuration:
```
@DBRider
@DataSet(value = "datasets/empty.yml", tableOrdering = {"table_1", "table_2", "table_3"}, useSequenceFiltering = false)
```
empty.yml
```
table_1:
table_2:
table_3:
```

Test class contains only:
```
@DataSet(value = "datasets/data.yml")
@ExpectedDataSet(value = "datasets/data_result.yml", orderBy = "id")
```
dbunit.yml
```
mergeDataSets: true
mergingStrategy: CLASS
```
This setup on real database run in 10 times faster, than with option `useSequenceFiltering = true`, all data from tables cleared before test and we should support only `value = "datasets/empty.yml", tableOrdering = {"table_1", "table_2", "table_3"}` in one place.

**Comment by rmpestano** [comment]
Really great news!
About the performance improvements, it is expected that useSequenceFiltering = true will slow down the tests, even more if you use a real database with lot of tables instead of a dedicated database for testing. On the other hand, useSequenceFiltering=true simplifies the configuration in most of the cases, so it's always a compromise, if you need tunning then you need to configure a bit more by using tableOrdering.

It would be nice if you could create a detailed blog post with all the gains you got with this configuration. I can create a new section on README with external resources and link the post there.  
 
Thank you very much for all the feedback. I'll release `1.18.0` with these changes in the next days.

**Comment by RomashkoVictor** [comment]
Thanks you too)
I have never shared my experience on any blogs. Maybe it's time to start)
If I create post I will share link with you)
