### ISSUE TITLE
As developer I want to add custom replacements for dataset

### ISSUE THREAD

**Issue by ahrytsiuk** [database-rider/database-rider#52]
Now there is [DateTimeReplacer](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/replacer/DateTimeReplacer.java) which allows us to have dynamic values for dates.

I think it would be handy to have more build-in replacers, for example `NullReplacer`.

Another nice feature - have ability to add your custom replacers into dataset configuration.
```
@DataSet(replacers={NullReplacer.class})
```
or may be
```
@DBUnit(replacers={NullReplacer.class})
```

**Comment by rmpestano** [comment]
Hi @ahrytsiuk,

Nice, would you like to contribute it? I'm in favor of @DBUnit(replacers={NullReplacer.class}) for custom replacer.

Thank you

**Comment by linux-china** [comment]
Any plan to add replacers={NullReplacer.class} for @DBUnit ?  it's a nice feature. 👍

**Comment by rmpestano** [comment]
Hi @linux-china,

It's a matter of someone pick this issue and contribute, the replacer itself is simple, something like:

```
ReplacementDataSet replacementDataSet = new ReplacementDataSet(dataSet);
replacementDataSet.addReplacementObject("[null]", null);
```

The configurable replacers that would require a bit more work. Basically [here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L396)  in performReplacements instead of always adding DateTimeReplacer we need to pick them from @DBUnit configuration. Note that the datetime replacer should come in the default replacers list.

**Comment by linux-china** [comment]
@rmpestano Now DateTimeReplacer and  [null] replacer  are very good.  Almost we don't need lots of replace features by default.  You can use Groovy script for some special case.   Now I use Unix timestamp a lot in database. I wonder could you add [UnixTimestamp] in  DateTimeReplacer.  Thanks.

**Comment by rmpestano** [comment]
@Hi @linux-china, you can't because the format is fixed, [see here ](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/replacer/DateTimeReplacer.java#L16).

If we had a way to provide replacers than you could try to load your "UnixTimestampReplacer". There are always corner cases that's why I think user defined replacers are a good idea.

**Comment by rmpestano** [comment]
Hi guys, anyone want to implement this, next version should be released in next week so this feature could be in this release. Thank you very much!
