### ISSUE TITLE
No algorithm found for <XYZ> in ScriptableTable

### ISSUE THREAD

**Issue by jenskreidler** [database-rider/database-rider#53]
Hi Rafael, 

since v1.2.3 the ScriptableTable has been introduced. After upgrading from 1.2.0 to 1.2.4 integration tests fail due to "No algorithm found for engine 'XYZ'". After a quick glance, the cause is the regex pattern identifying a scripted column value. 
I have got coumns as follows in yaml:

Table:
- mycol: "XZY:123"
[...]

It would be smart to improve the engine detection behaviour anyhow, in order to support column values that contain a colon.

**Comment by rmpestano** [comment]
Hi @jenskreidler,

I think we can just log a warn [here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/api/dataset/ScriptableTable.java#L83) instead of throwing an exception because later we will not eval if script engine is null. WDYT?

thanks for reporting.

**Comment by jenskreidler** [comment]
Hi @rmpestano ,

yes, I'd would be OK to log a warning only since any null-script-engine doesn't imply an other side-effects like NPEs etc.

**Comment by rmpestano** [comment]
Thank you @jenskreidler, v1.2.5 should be on maven central soon.
