### ISSUE TITLE
Support  Spring Boot 3

### ISSUE THREAD

**Issue by yuhaibohotmail** [database-rider/database-rider#552]
Spring boot 3 uses Jakarta EE artifacts ([see here](https://www.baeldung.com/spring-boot-3-migration#2-jakarta-ee-10)). Right now rider is not compatible with Jakarta persistence. TODO: provide sample app which uses SpringBoot 3 and share the error stacktrace

**Comment by rmpestano** [comment]
Hey, Quarkus 3 is being worked [here](https://github.com/database-rider/database-rider/issues/496#issuecomment-1572701198), please help testing it. SpringBoot 3 will come next, would be nice if you guys can share the issues and possible fixes as in the Quarkus issue

**Comment by yuhaibohotmail** [comment]
Hey,it works for me with Quarkus 3 .Great work!

**Comment by renannprado** [comment]
@rmpestano I know it's an open source project, and I cannot demand anything. But I just would like to know whether you have any expectations of when the integration with spring boot 3 will be fixed? I didn't try out on my own yet, but I'm assuming right now it's not working currently (that's why this issue exists).

As soon as I have time to try on my own, I'll do that and report here. 

Thanks for maintaining it!
