### ISSUE TITLE
Order of rows in @ExpectedDataSet

### ISSUE THREAD

**Issue by jenskreidler** [database-rider/database-rider#71]
As a test developer, I want to prepare or sort the row-per-table-order since it is not guaranteed how JPA does physically persists an associated collection for instance.

Assume you have got an entity A with a field of entity B using @OneToMany association. A test is written that creates one object of A associated with six objects of B. I'd like to predict the order of "B's" in the dataset configured in "@ExpectedDataSet(value={foo.yml})" because the occurrence of rows of B's described in foo.yml are as they are.

**Comment by rmpestano** [comment]
Hi @jenskreidler,

can you provide a PR with a (failing) test which describes this issue?  The test [can be here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/ExpectedDataSetIt.java). Or you can attach a small sample which reproduces the issue here.


Thank you in advance.

**Comment by rmpestano** [comment]
Fixed by #107
